version: "3.9"

services:
  db:
    image: postgres:15
    container_name: music_ai_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi_app:
    build: .
    container_name: top_music_ai
    command: sh -c "uvicorn app.manage:init --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./topmediai_user_data:/app/topmediai_user_data
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres+asyncpg://postgres:postgres@db:5432/music_ai
      PYTHONUNBUFFERED: 1

volumes:
  postgres_data:
