"""new_fields

Revision ID: 9528279fb3a1
Revises: d1ef1862bc75
Create Date: 2025-07-10 19:06:46.930029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9528279fb3a1'
down_revision: Union[str, Sequence[str], None] = 'd1ef1862bc75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voices', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('voices', sa.Column('avatar_url_webp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voices', 'avatar_url_webp')
    op.drop_column('voices', 'avatar_url')
    # ### end Alembic commands ###
