"""added audition_url

Revision ID: f5c3c963a670
Revises: 9528279fb3a1
Create Date: 2025-07-21 23:15:44.068942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c3c963a670'
down_revision: Union[str, Sequence[str], None] = '9528279fb3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voices', sa.Column('audition_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voices', 'audition_url')
    # ### end Alembic commands ###
